### ISSUE TITLE
Will there be any plan for the to do list on README.md?

### ISSUE THREAD

**Issue by lez14004** [CarnoZhao/Kaggle-UWMGIT#6]
Hi Carno,

Congratulations to the Championship! Thank you for sharing this elegant training pipeline during the competition. Will there be any plan to update the whole thing, like including the try and error part? (sorry...伸手党了）

**Comment by CarnoZhao** [comment]
Hi @lez14004 ,

I think I will update my solution code (inluding our team codes ?) in next few days because I have something else to work with currently.

I will not include try and error part in this repo, instead, only the final solution. I have trained 100+ models, with even more various experiments. It is hard to summarize how I come up with the final solution step by step.

**Comment by lez14004** [comment]
Understood. Still very appreciate for your open source spirit and instant reply. 
All the best.
